services:
  - type: worker
    name: raven-filter-bot
    runtime: python
    plan: pro ultra
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: SESSION_STRING
        sync: false
      - key: CAPTION_FILTER
        value: "Stripe 1$ Charge||Braintree Charge"
      - key: DELETE_GATEWAYS
        value: "Stripe Auth"
      - key: ALLOWED_CHAT
        value: "-1003727002856"
